### ISSUE TITLE
Update google chrome message

### ISSUE THREAD

**Issue by nephaste** [mjnielsen/WhatsApp-electron-appimage#1]
Hi Thanks for WhatsApp

just built a qpkg for Qnap and HDStation (ubuntu1804), starting appimage getting message

WhatsApp Works with Google chrome 36+
to use WhatsApp, updtae Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera

anything you can do ?

**Comment by mjnielsen** [comment]
Sorry, I missed this comment when it was posted. If it's still of interest (and for anyone else who wants to know) this can be fixed by setting the user agent in main.js. The new version that I just pushed no longer has this error.
